package request;

public enum RequestType {
	LOGIN,
	SEND_MESSAGE,
	LOGIN_SUCCESSFULLY,
	MESSAGE,
	GET_FRIEND_LIST,
	SERVER_MESSAGE,
	GET_SEARCH_ADDFRIEND_LIST,
	SEND_FRIEND_REQUEST,
	FRIEND_REQUEST,
	ACCEPT_FR,
	REFUSE_FR,
	SEND_MESSAGE_STATUS,
	SEEN_STATUS,
	UPDATE_F_STATUS,
	TYPING,
	SEND_VIDEO,
	SEND_AUDIO
}
